### ISSUE TITLE
Incompatibility with `packaging` 22.0

### ISSUE THREAD

**Issue by lhoenig** [Emily3403/isisdl#18]
They [removed](https://github.com/pypa/packaging/pull/407) `LegacyVersion`, which is used in `isisdl` (utils.py).

**Comment by Emily3403** [comment]
Thanks for the hint, should be fixed now ^^

**Comment by lhoenig** [comment]
Thanks! :)

**Comment by Emily3403** [comment]
These kinds of problems (breaking changes in a dependency) should now be fixed as I changed the `>=` in the requirements to a `~=`. This operator [respects the semantic versioning](https://stackoverflow.com/a/39590286) and will keep backwards compatibility.
