### ISSUE TITLE
Feature Request: Propagation of choice implications to posterior prompts in config wizard

### ISSUE THREAD

**Issue by MatteoGaetzner** [Emily3403/isisdl#5]
Fist of all: Thanks for developing this super useful tool!

Feature request:
Currently selecting for example cleaned file paths e.g. 'Course one-a' -> 'CourseOneA' doesn't influence posterior config wizard pages. 
It would be awesome if that could be implemented.

**Comment by Emily3403** [comment]
That is a great idea ^^
