### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by Emily3403** [Emily3403/isisdl#6]
Currently isisdl is not working for MacOS. The Problem is somewhere in the underlying socket implementation. Since I don't own a Mac this problem is kinda hard for me to debug. So if anyone with Mac would like to help it would be greatly appreciated.

**Comment by ghost** [comment]
I am using isisdl on macOS 12.3.1 and it's working like a charm.

**Comment by Emily3403** [comment]
Thanks for the feedback. It seams as if this issue is a problem with anaconda - not MacOS. Both systems, which I tested on had anaconda as a python provider instead of CPython. 

If the anaconda implementation does not work, I won't support it. CPython is fine.

**Comment by ghost** [comment]
Yup. I was using Python 3.10 with the respective pip from MacPorts.
